// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa_2_oZ3A5GJeh85r5ClgpAByRhO9d7J8',
    appId: '1:15219795494:web:ecf508a6f3ad951748a8e7',
    messagingSenderId: '15219795494',
    projectId: 'sign-up-page-b86b1',
    authDomain: 'sign-up-page-b86b1.firebaseapp.com',
    storageBucket: 'sign-up-page-b86b1.appspot.com',
    measurementId: 'G-LS23E7Y8S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTW2CG-_Puw4DA68_CwtiKU3v1DuTzPdc',
    appId: '1:15219795494:android:4d193759d1c1b2c848a8e7',
    messagingSenderId: '15219795494',
    projectId: 'sign-up-page-b86b1',
    storageBucket: 'sign-up-page-b86b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV1bG9-0mhxJtRz1ZrXAXuObv0HCqGjE4',
    appId: '1:15219795494:ios:1a1255e717223e3448a8e7',
    messagingSenderId: '15219795494',
    projectId: 'sign-up-page-b86b1',
    storageBucket: 'sign-up-page-b86b1.appspot.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV1bG9-0mhxJtRz1ZrXAXuObv0HCqGjE4',
    appId: '1:15219795494:ios:1a1255e717223e3448a8e7',
    messagingSenderId: '15219795494',
    projectId: 'sign-up-page-b86b1',
    storageBucket: 'sign-up-page-b86b1.appspot.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa_2_oZ3A5GJeh85r5ClgpAByRhO9d7J8',
    appId: '1:15219795494:web:9248784e992e13bc48a8e7',
    messagingSenderId: '15219795494',
    projectId: 'sign-up-page-b86b1',
    authDomain: 'sign-up-page-b86b1.firebaseapp.com',
    storageBucket: 'sign-up-page-b86b1.appspot.com',
    measurementId: 'G-X7D8JM2KRW',
  );

}